CREATE TABLE ARK_TREE_CLOSURE_LONG (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   ancestor_id BIGINT NOT NULL,
   descendant_id BIGINT NOT NULL,
   depth INT NOT NULL,
   biz_table VARCHAR(64) NOT NULL
);

CREATE TABLE ARK_TREE_CLOSURE_STRING (
   id VARCHAR(36) PRIMARY KEY,
   ancestor_id VARCHAR(36) NOT NULL,
   descendant_id VARCHAR(36) NOT NULL,
   depth INT NOT NULL,
   biz_table VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEST_PRODUCT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(100),
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE TEST_DEPT (
      id BIGINT PRIMARY KEY AUTO_INCREMENT,
      parent_id BIGINT,
      name VARCHAR(255) NOT NULL,
      IS_LEAF INT DEFAULT 1 NOT NULL,
      SORT_ORDER BIGINT DEFAULT 0 NOT NULL,
      status INT DEFAULT 0 NOT NULL,
      create_time TIMESTAMP,
      update_time TIMESTAMP,
      create_by VARCHAR(255),
      update_by VARCHAR(255)
);

COMMENT ON COLUMN TEST_DEPT.id IS '主键ID';
COMMENT ON COLUMN TEST_DEPT.parent_id IS '父部门ID';
COMMENT ON COLUMN TEST_DEPT.name IS '部门名称';
COMMENT ON COLUMN TEST_DEPT.IS_LEAF IS '是否为叶子节点 (1:是, 0:否)';
COMMENT ON COLUMN TEST_DEPT.SORT_ORDER IS '排序号';
COMMENT ON COLUMN TEST_DEPT.status IS '状态 (0:启用, 1:禁用)';
COMMENT ON COLUMN TEST_DEPT.create_time IS '创建时间';
COMMENT ON COLUMN TEST_DEPT.update_time IS '更新时间';
COMMENT ON COLUMN TEST_DEPT.create_by IS '创建人';
COMMENT ON COLUMN TEST_DEPT.update_by IS '更新人';