
CREATE TABLE IF NOT EXISTS ARK_TREE_CLOSURE_LONG (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   ancestor_id BIGINT NOT NULL,
   descendant_id BIGINT NOT NULL,
   depth INT NOT NULL,
   biz_table VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARK_TREE_CLOSURE_STRING (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   ancestor_id VARCHAR(36) NOT NULL,
   descendant_id VARCHAR(36) NOT NULL,
   depth INT NOT NULL,
   biz_table VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEST_PRODUCT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(100),
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS TEST_DEPT (
      id VARCHAR(36) PRIMARY KEY,
      parent_id VARCHAR(36),
      name VARCHAR(255) NOT NULL,
      IS_LEAF INT DEFAULT 1 NOT NULL,
      SORT_ORDER BIGINT DEFAULT 0 NOT NULL,
      status INT DEFAULT 0 NOT NULL,
      create_time TIMESTAMP,
      update_time TIMESTAMP,
      create_by VARCHAR(255),
      update_by VARCHAR(255)
);
